apiVersion: apps/v1 #defining the the version
kind: Deployment  #defining the kind of the object
metadata:    #some extra information about the object
  name: comments-depl
spec:  #specifications of the Deployment
  replicas: 1  #number of copies of the pod(which are also known as containers)
  selector:  #selector to give a unique name for selection purpose
    matchLabels:
      app: comments
  template: #here defining the lable of template for selection purpose
    metadata:
      labels:
        app: comments
    spec: #specifications of the pdf for example containers
      containers:
        - name: comments #name of the container that will inside the kubernetes cluster
          image: manmeetmoudgill/comments:latest #name of the image
--- #this is used to add more than an object in a single file
apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip-srv
spec:
  selector:
    app: comments
  ports:
    - name: posts
      protocol: TCP
      port: 4001
      targetPort: 4001